// This file is auto-generated by FluidKit. Do not edit.
// Any changes will be overwritten on the next build.
import { Agent, fetch as _undici_fetch } from 'undici';

export const BASE_URL = "http://localhost:8000";

const _fk_agent = new Agent({
  connections: null,
  pipelining: 1,
  keepAliveTimeout: 30_000,
  keepAliveMaxTimeout: 60_000,
});

export function _fk_fetch(url: string, init: object): Promise<Response> {
  return _undici_fetch(url, { ...init, dispatcher: _fk_agent }) as unknown as Response;
}
