// This file is auto-generated by FluidKit. Do not edit.
// Any changes will be overwritten on the next build.

export namespace test_ftypes {
  export interface User {
    name: string;
    age: number;
  }

}
