from fluidkit.models import FieldAnnotation, BaseType, ContainerType


GENERATED_FILE_WARNING = """// This file is auto-generated by FluidKit. Do not edit.
// Any changes will be overwritten on the next build.
"""


class TSWriter:
    def __init__(self):
        self._lines: list[str] = []
        self._indent: int = 0

    def line(self, text: str = ""):
        prefix = "  " * self._indent
        self._lines.append(f"{prefix}{text}" if text else "")

    def blank(self):
        self._lines.append("")

    def indent(self):
        self._indent += 1

    def dedent(self):
        self._indent -= 1

    def block(self, header: str, closing: str = "}"):
        return _Block(self, header, closing)

    def render(self) -> str:
        return "\n".join(self._lines) + "\n"


class _Block:
    def __init__(self, writer: TSWriter, header: str, closing: str):
        self._writer = writer
        self._header = header
        self._closing = closing

    def __enter__(self):
        self._writer.line(self._header)
        self._writer.indent()
        return self._writer

    def __exit__(self, *_):
        self._writer.dedent()
        self._writer.line(self._closing)


def annotation_to_ts(ann: FieldAnnotation) -> str:
    if ann.base_type is not None:
        if ann.base_type is BaseType.FILE:
            return "File"
        return ann.base_type.value

    if ann.custom_type is not None:
        return ann.custom_type

    match ann.container:
        case ContainerType.OPTIONAL:
            return f"{annotation_to_ts(ann.args[0])} | null"
        case ContainerType.ARRAY:
            inner = annotation_to_ts(ann.args[0])
            if ann.args[0].container in (ContainerType.UNION, ContainerType.OPTIONAL):
                return f"({inner})[]"
            return f"{inner}[]"
        case ContainerType.RECORD:
            return f"Record<{annotation_to_ts(ann.args[0])}, {annotation_to_ts(ann.args[1])}>"
        case ContainerType.TUPLE:
            return f"[{', '.join(annotation_to_ts(a) for a in ann.args)}]"
        case ContainerType.UNION:
            return " | ".join(annotation_to_ts(a) for a in ann.args)
        case ContainerType.LITERAL:
            parts = []
            for v in ann.literal_values:
                if isinstance(v, str):
                    parts.append(f'"{v}"')
                elif isinstance(v, bool):
                    parts.append(str(v).lower())
                else:
                    parts.append(str(v))
            return " | ".join(parts)

    return "any"


def module_to_namespace(module: str) -> str:
    for prefix in ["src.lib.", "src.routes.", "src."]:
        if module.startswith(prefix):
            module = module[len(prefix):]
            break
    if module == "__main__":
        return "main_ftypes"
    return module.replace(".", "_") + "_ftypes"
