// This file is auto-generated by FluidKit. Do not edit.
// Any changes will be overwritten on the next build.

export namespace demo_ftypes {
  export interface Post {
    id: number;
    title: string;
    content: string;
  }

}
