// This file is auto-generated by FluidKit. Do not edit.
// Any changes will be overwritten on the next build.

import { error, redirect } from '@sveltejs/kit';
import { command, form, query, getRequestEvent } from '$app/server';
import { extractFiles, getRemoteFunction, hasFiles, registerRemoteFunction } from '$fluidkit/registry';
import { BASE_URL } from '$fluidkit/config';

export const get_posts = query(async () => {
  const { cookies: _fk_cookies } = getRequestEvent();
  const _fk_res = await fetch(`${BASE_URL}/remote/src/lib/demo/get_posts`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Cookie': _fk_cookies.getAll().map(c => `${c.name}=${c.value}`).join('; '),
    },
    body: JSON.stringify({}),
  });
  if (!_fk_res.ok) {
    const _fk_err = await _fk_res.json();
    if (_fk_err.__fluidkit_error) console.error(_fk_err.__fluidkit_error.traceback);
    error(_fk_res.status, _fk_err.message ?? 'Unexpected error');
  }
  const _fk_body = await _fk_res.json();
  return _fk_body.result as any;
});

export const like_post = command('unchecked', async (post_id: number) => {
  const { cookies: _fk_cookies } = getRequestEvent();
  const _fk_res = await fetch(`${BASE_URL}/remote/src/lib/demo/like_post`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Cookie': _fk_cookies.getAll().map(c => `${c.name}=${c.value}`).join('; '),
    },
    body: JSON.stringify({ post_id }),
  });
  if (!_fk_res.ok) {
    const _fk_err = await _fk_res.json();
    if (_fk_err.__fluidkit_error) console.error(_fk_err.__fluidkit_error.traceback);
    error(_fk_res.status, _fk_err.message ?? 'Unexpected error');
  }
  const _fk_body = await _fk_res.json();
  for (const { name: _fk_cn, value: _fk_cv, ..._fk_co } of _fk_body.__fluidkit?.cookies ?? []) {
    _fk_cookies.set(_fk_cn, _fk_cv, _fk_co);
  }
  for (const { key: _fk_key, args: _fk_args, data: _fk_data } of _fk_body.__fluidkit?.mutations ?? []) {
    const _fk_fn = getRemoteFunction(_fk_key);
    if (_fk_fn) _fk_fn(_fk_args, _fk_data);
  }
  return _fk_body.result as any;
});

export const add_post = form('unchecked', async (data) => {
  const { cookies: _fk_cookies } = getRequestEvent();

  let _fk_res: Response;
  if (!hasFiles(data)) {
    _fk_res = await fetch(`${BASE_URL}/remote/src/lib/demo/add_post`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Cookie': _fk_cookies.getAll().map(c => `${c.name}=${c.value}`).join('; '),
      },
      body: JSON.stringify(data),
    });
  } else {
    const { json: _fk_json, files: _fk_files } = extractFiles(data);
    const _fk_form = new FormData();
    _fk_form.append('__fluidkit_data', JSON.stringify(_fk_json));
    for (const [_fk_path, _fk_file] of _fk_files) {
      _fk_form.append(_fk_path, _fk_file);
    }
    _fk_res = await fetch(`${BASE_URL}/remote/src/lib/demo/add_post`, {
      method: 'POST',
      headers: {
        'Cookie': _fk_cookies.getAll().map(c => `${c.name}=${c.value}`).join('; '),
      },
      body: _fk_form,
    });
  }

  if (!_fk_res.ok) {
    const _fk_err = await _fk_res.json();
    if (_fk_err.__fluidkit_error) console.error(_fk_err.__fluidkit_error.traceback);
    error(_fk_res.status, _fk_err.message ?? 'Unexpected error');
  }
  const _fk_body = await _fk_res.json();
  for (const { name: _fk_cn, value: _fk_cv, ..._fk_co } of _fk_body.__fluidkit?.cookies ?? []) {
    _fk_cookies.set(_fk_cn, _fk_cv, _fk_co);
  }
  if ('redirect' in _fk_body) redirect(_fk_body.redirect.status, _fk_body.redirect.location);
  for (const { key: _fk_key, args: _fk_args, data: _fk_data } of _fk_body.__fluidkit?.mutations ?? []) {
    const _fk_fn = getRemoteFunction(_fk_key);
    if (_fk_fn) _fk_fn(_fk_args, _fk_data);
  }
  return _fk_body.result as any;
});

registerRemoteFunction('src.lib.demo#get_posts', (_fk_args: any, _fk_data: any) => {
  get_posts().set(_fk_data);
});
