// This file is auto-generated by FluidKit. Do not edit.
// Any changes will be overwritten on the next build.

import { error, redirect } from '@sveltejs/kit';
import { command, form, query, getRequestEvent } from '$app/server';
import { getRemoteFunction, registerRemoteFunction } from '$fluidkit/registry';
import { BASE_URL, _fk_fetch } from '$fluidkit/config';
import { signRequest } from '$fluidkit/auth';

/**
 * Fetch all posts.
 *
 * ---
 * @see [`src/lib/demo.py` . `@query`](./demo.py)
 * @see [Fluidkit Docs #query](https://fluidkit.github.io/docs/query)
 *
 * ---
 *
 * @example
 * ```svelte
 * <script>
 *   import { get_posts } from '$lib/demo.remote';
 * </script>
 *
 * {await get_posts()}
 * ```
 */
export const get_posts = query(async () => {
  const _fk_event = getRequestEvent();
  const { cookies: _fk_cookies } = _fk_event;
  const _fk_context = {
    url: _fk_event.url.href,
    method: _fk_event.request.method,
    headers: Object.fromEntries(_fk_event.request.headers),
    cookies: _fk_cookies.getAll(),
    is_remote: true,
  };
  const _fk_res = await _fk_fetch(`${BASE_URL}/remote/src/lib/demo/get_posts`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Cookie': _fk_cookies.getAll().map(c => `${c.name}=${c.value}`).join('; '),
      'X-FluidKit-Token': signRequest(),
    },
    body: JSON.stringify({ __fk_payload: {}, __fk_context: _fk_context }),
  });
  if (!_fk_res.ok) {
    const _fk_err = await _fk_res.json();
    if (_fk_err.__fluidkit_error) console.error(_fk_err.__fluidkit_error.traceback);
    error(_fk_res.status, _fk_err.message ?? 'Unexpected error');
  }
  const _fk_body = await _fk_res.json();
  if (_fk_body.__fk_locals) {
    Object.assign(_fk_event.locals, _fk_body.__fk_locals);
  }
  return _fk_body.result as any;
});

/**
 * Like a post by ID.
 *
 * ---
 * @see [`src/lib/demo.py` . `@command`](./demo.py)
 * @see [Fluidkit Docs #command](https://fluidkit.github.io/docs/command)
 *
 * ---
 *
 * @example
 * ```svelte
 * <script>
 *   import { like_post } from '$lib/demo.remote';
 * </script>
 *
 * <button onclick={async () => await like_post(post_id)}>
 *   Like Post
 * </button>
 * ```
 */
export const like_post = command('unchecked', async (post_id: number) => {
  const _fk_event = getRequestEvent();
  const { cookies: _fk_cookies } = _fk_event;
  const _fk_context = {
    url: _fk_event.url.href,
    method: _fk_event.request.method,
    headers: Object.fromEntries(_fk_event.request.headers),
    cookies: _fk_cookies.getAll(),
    is_remote: true,
  };
  const _fk_res = await _fk_fetch(`${BASE_URL}/remote/src/lib/demo/like_post`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Cookie': _fk_cookies.getAll().map(c => `${c.name}=${c.value}`).join('; '),
      'X-FluidKit-Token': signRequest(),
    },
    body: JSON.stringify({ __fk_payload: { post_id }, __fk_context: _fk_context }),
  });
  if (!_fk_res.ok) {
    const _fk_err = await _fk_res.json();
    if (_fk_err.__fluidkit_error) console.error(_fk_err.__fluidkit_error.traceback);
    error(_fk_res.status, _fk_err.message ?? 'Unexpected error');
  }
  const _fk_body = await _fk_res.json();
  for (const { name: _fk_cn, value: _fk_cv, ..._fk_co } of _fk_body.__fk_cookies ?? []) {
    _fk_event.cookies.set(_fk_cn, _fk_cv, _fk_co);
  }
  if (_fk_body.__fk_locals) {
    Object.assign(_fk_event.locals, _fk_body.__fk_locals);
  }
  for (const { key: _fk_key, args: _fk_args, data: _fk_data } of _fk_body.__fluidkit?.mutations ?? []) {
    const _fk_fn = getRemoteFunction(_fk_key);
    if (_fk_fn) _fk_fn(_fk_args, _fk_data);
  }
  return _fk_body.result as any;
});

/**
 * Add a new post.
 *
 * ---
 * @see [`src/lib/demo.py` . `@form`](./demo.py)
 * @see [Fluidkit Docs #form](https://fluidkit.github.io/docs/form)
 *
 * ---
 *
 * @example
 * ```svelte
 * <script>
 *   import { add_post } from '$lib/demo.remote';
 * </script>
 *
 * <form {...add_post}>
 *   <input {...add_post.fields.title.as('text')} />
 *   <input {...add_post.fields.content.as('text')} />
 *   <button>Submit</button>
 * </form>
 * ```
 */
export const add_post = form('unchecked', async (data) => {
  const _fk_event = getRequestEvent();
  const { cookies: _fk_cookies } = _fk_event;
  const _fk_context = {
    url: _fk_event.url.href,
    method: _fk_event.request.method,
    headers: Object.fromEntries(_fk_event.request.headers),
    cookies: _fk_cookies.getAll(),
    is_remote: true,
  };

  const _fk_res = await _fk_fetch(`${BASE_URL}/remote/src/lib/demo/add_post`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Cookie': _fk_cookies.getAll().map(c => `${c.name}=${c.value}`).join('; '),
      'X-FluidKit-Token': signRequest(),
    },
    body: JSON.stringify({ __fk_payload: data, __fk_context: _fk_context }),
  });

  if (!_fk_res.ok) {
    const _fk_err = await _fk_res.json();
    if (_fk_err.__fluidkit_error) console.error(_fk_err.__fluidkit_error.traceback);
    error(_fk_res.status, _fk_err.message ?? 'Unexpected error');
  }
  const _fk_body = await _fk_res.json();
  for (const { name: _fk_cn, value: _fk_cv, ..._fk_co } of _fk_body.__fk_cookies ?? []) {
    _fk_event.cookies.set(_fk_cn, _fk_cv, _fk_co);
  }
  if (_fk_body.__fk_locals) {
    Object.assign(_fk_event.locals, _fk_body.__fk_locals);
  }
  if ('redirect' in _fk_body) redirect(_fk_body.redirect.status, _fk_body.redirect.location);
  for (const { key: _fk_key, args: _fk_args, data: _fk_data } of _fk_body.__fluidkit?.mutations ?? []) {
    const _fk_fn = getRemoteFunction(_fk_key);
    if (_fk_fn) _fk_fn(_fk_args, _fk_data);
  }
  return _fk_body.result as any;
});

registerRemoteFunction('src.lib.demo#get_posts', (_fk_args: any, _fk_data: any) => {
  get_posts().set(_fk_data);
});
