// This file is auto-generated by FluidKit. Do not edit.
// Any changes will be overwritten on the next build.

import { error, redirect } from '@sveltejs/kit';
import { command, form, query, getRequestEvent } from '$app/server';
import { extractFiles, getRemoteFunction, hasFiles, registerRemoteFunction } from '$fluidkit/registry';
import { BASE_URL } from '$fluidkit/config';
import type { test_ftypes } from '$fluidkit/schema';

type User = test_ftypes.User;

/**
 * Should reject non-int values.
 *
 * @returns `number`
 *
 * ---
 * @see [`src/lib/test.py` . `@query`](./test.py)
 * @see [Fluidkit Docs #query](https://fluidkit.github.io/docs/query)
 *
 * ---
 *
 * @example
 * ```svelte
 * <script>
 *   import { get_number } from '$lib/test.remote';
 * </script>
 *
 * <p>{await get_number(n)}</p>
 * ```
 */
export const get_number = query('unchecked', async (n: number) => {
  const { cookies: _fk_cookies } = getRequestEvent();
  const _fk_res = await fetch(`${BASE_URL}/remote/src/lib/test/get_number`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Cookie': _fk_cookies.getAll().map(c => `${c.name}=${c.value}`).join('; '),
    },
    body: JSON.stringify({ n }),
  });
  if (!_fk_res.ok) {
    const _fk_err = await _fk_res.json();
    if (_fk_err.__fluidkit_error) console.error(_fk_err.__fluidkit_error.traceback);
    error(_fk_res.status, _fk_err.message ?? 'Unexpected error');
  }
  const _fk_body = await _fk_res.json();
  return _fk_body.result as number;
});

/**
 * Should reject non-str name and non-bool loud.
 *
 * @returns `string`
 *
 * ---
 * @see [`src/lib/test.py` . `@query`](./test.py)
 * @see [Fluidkit Docs #query](https://fluidkit.github.io/docs/query)
 *
 * ---
 *
 * @example
 * ```svelte
 * <script>
 *   import { get_greeting } from '$lib/test.remote';
 * </script>
 *
 * <p>{await get_greeting({ name, loud })}</p>
 * ```
 */
export const get_greeting = query('unchecked', async ({name, loud}: {name: string, loud: boolean}) => {
  const { cookies: _fk_cookies } = getRequestEvent();
  const _fk_res = await fetch(`${BASE_URL}/remote/src/lib/test/get_greeting`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Cookie': _fk_cookies.getAll().map(c => `${c.name}=${c.value}`).join('; '),
    },
    body: JSON.stringify({ name, loud }),
  });
  if (!_fk_res.ok) {
    const _fk_err = await _fk_res.json();
    if (_fk_err.__fluidkit_error) console.error(_fk_err.__fluidkit_error.traceback);
    error(_fk_res.status, _fk_err.message ?? 'Unexpected error');
  }
  const _fk_body = await _fk_res.json();
  return _fk_body.result as string;
});

/**
 * Should validate full Pydantic model.
 *
 * @returns `Record<string, any>`
 *
 * ---
 * @see [`src/lib/test.py` . `@command`](./test.py)
 * @see [Fluidkit Docs #command](https://fluidkit.github.io/docs/command)
 *
 * ---
 *
 * @example
 * ```svelte
 * <script>
 *   import { create_user } from '$lib/test.remote';
 * </script>
 *
 * <button onclick={async () => {
 *   const result = await create_user(user);
 * }}>
 *   Create User
 * </button>
 * ```
 */
export const create_user = command('unchecked', async (user: User) => {
  const { cookies: _fk_cookies } = getRequestEvent();
  const _fk_res = await fetch(`${BASE_URL}/remote/src/lib/test/create_user`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Cookie': _fk_cookies.getAll().map(c => `${c.name}=${c.value}`).join('; '),
    },
    body: JSON.stringify({ user }),
  });
  if (!_fk_res.ok) {
    const _fk_err = await _fk_res.json();
    if (_fk_err.__fluidkit_error) console.error(_fk_err.__fluidkit_error.traceback);
    error(_fk_res.status, _fk_err.message ?? 'Unexpected error');
  }
  const _fk_body = await _fk_res.json();
  for (const { name: _fk_cn, value: _fk_cv, ..._fk_co } of _fk_body.__fluidkit?.cookies ?? []) {
    _fk_cookies.set(_fk_cn, _fk_cv, _fk_co);
  }
  for (const { key: _fk_key, args: _fk_args, data: _fk_data } of _fk_body.__fluidkit?.mutations ?? []) {
    const _fk_fn = getRemoteFunction(_fk_key);
    if (_fk_fn) _fk_fn(_fk_args, _fk_data);
  }
  return _fk_body.result as Record<string, any>;
});

/**
 * Should reject non-str user_id.
 *
 * @returns `User | null`
 *
 * ---
 * @see [`src/lib/test.py` . `@query`](./test.py)
 * @see [Fluidkit Docs #query](https://fluidkit.github.io/docs/query)
 *
 * ---
 *
 * @example
 * ```svelte
 * <script>
 *   import { find_user } from '$lib/test.remote';
 *
 *   const user = $derived(await find_user(user_id));
 * </script>
 *
 * {#if user}
 *   <p>Name: {user.name}</p>
 *   <p>Age: {user.age}</p>
 * {:else}
 *   <p>User not found</p>
 * {/if}
 * ```
 */
export const find_user = query('unchecked', async (user_id: string) => {
  const { cookies: _fk_cookies } = getRequestEvent();
  const _fk_res = await fetch(`${BASE_URL}/remote/src/lib/test/find_user`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Cookie': _fk_cookies.getAll().map(c => `${c.name}=${c.value}`).join('; '),
    },
    body: JSON.stringify({ user_id }),
  });
  if (!_fk_res.ok) {
    const _fk_err = await _fk_res.json();
    if (_fk_err.__fluidkit_error) console.error(_fk_err.__fluidkit_error.traceback);
    error(_fk_res.status, _fk_err.message ?? 'Unexpected error');
  }
  const _fk_body = await _fk_res.json();
  return _fk_body.result as User | null;
});

/**
 * Should validate rating as int, message as str.
 *
 * ---
 * @see [`src/lib/test.py` . `@form`](./test.py)
 * @see [Fluidkit Docs #form](https://fluidkit.github.io/docs/form)
 *
 * ---
 *
 * @example
 * ```svelte
 * <script>
 *   import { submit_feedback } from '$lib/test.remote';
 * </script>
 *
 * <form {...submit_feedback}>
 *   <input {...submit_feedback.fields.rating.as('number')} />
 *   <input {...submit_feedback.fields.message.as('text')} />
 *   <button>Submit</button>
 * </form>
 * ```
 */
export const submit_feedback = form('unchecked', async (data) => {
  const { cookies: _fk_cookies } = getRequestEvent();

  let _fk_res: Response;
  if (!hasFiles(data)) {
    _fk_res = await fetch(`${BASE_URL}/remote/src/lib/test/submit_feedback`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Cookie': _fk_cookies.getAll().map(c => `${c.name}=${c.value}`).join('; '),
      },
      body: JSON.stringify(data),
    });
  } else {
    const { json: _fk_json, files: _fk_files } = extractFiles(data);
    const _fk_form = new FormData();
    _fk_form.append('__fluidkit_data', JSON.stringify(_fk_json));
    for (const [_fk_path, _fk_file] of _fk_files) {
      _fk_form.append(_fk_path, _fk_file);
    }
    _fk_res = await fetch(`${BASE_URL}/remote/src/lib/test/submit_feedback`, {
      method: 'POST',
      headers: {
        'Cookie': _fk_cookies.getAll().map(c => `${c.name}=${c.value}`).join('; '),
      },
      body: _fk_form,
    });
  }

  if (!_fk_res.ok) {
    const _fk_err = await _fk_res.json();
    if (_fk_err.__fluidkit_error) console.error(_fk_err.__fluidkit_error.traceback);
    error(_fk_res.status, _fk_err.message ?? 'Unexpected error');
  }
  const _fk_body = await _fk_res.json();
  for (const { name: _fk_cn, value: _fk_cv, ..._fk_co } of _fk_body.__fluidkit?.cookies ?? []) {
    _fk_cookies.set(_fk_cn, _fk_cv, _fk_co);
  }
  if ('redirect' in _fk_body) redirect(_fk_body.redirect.status, _fk_body.redirect.location);
  for (const { key: _fk_key, args: _fk_args, data: _fk_data } of _fk_body.__fluidkit?.mutations ?? []) {
    const _fk_fn = getRemoteFunction(_fk_key);
    if (_fk_fn) _fk_fn(_fk_args, _fk_data);
  }
  return _fk_body.result as any;
});

registerRemoteFunction('src.lib.test#get_number', (_fk_args: any, _fk_data: any) => {
  get_number(_fk_args).set(_fk_data);
});
registerRemoteFunction('src.lib.test#get_greeting', (_fk_args: any, _fk_data: any) => {
  get_greeting(_fk_args).set(_fk_data);
});
registerRemoteFunction('src.lib.test#find_user', (_fk_args: any, _fk_data: any) => {
  find_user(_fk_args).set(_fk_data);
});
